### ISSUE TITLE
Generate new pos/neg sentences

### ISSUE THREAD

**Issue by madewild** [madewild/cfg#5]
We have some sentences defined manually:
https://github.com/madewild/cfg/blob/master/pos.txt
https://github.com/madewild/cfg/blob/master/neg.txt

Would be good to write a generator creating new (in)valid sentences automatically. Then we just have to select them instead of inventing them from scratch.

**Comment by madewild** [comment]
Or easier manually?

**Comment by devironl** [comment]
cf. pull request
